DROP TABLE IF EXISTS PURCHASE;
DROP TABLE IF EXISTS SUBSCRIPTION;
CREATE TABLE PURCHASE(id PRIMARY KEY, "timestamp" TIMESTAMP , msisdn integer);
CREATE TABLE SUBSCRIPTION(id PRIMARY KEY, "timestamp" TIMESTAMP , msisdn integer);